# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER stone.huang@hyweb.com.tw

# Copy custom configuration file from the current directory
COPY files/nginx.conf /etc/nginx/nginx.conf



